### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by androideveloper** [nordicway/moji#8]
Hi, I am trying to use your library but I get Exception in thread "main" java.net.ConnectException: Connection timed out: connect. How can I resolve this issue?

**Comment by nordicway** [comment]
Hi. That might just be a temporary problem with your connection to the Moss server. If it does not go away after some time, here are some steps to track down the issue:
- check your firewall settings and logs, if there is any
- verify manually that your connection to the Moss server works (eg. "telnet moss.stanford.edu 7690" on the Windows command line)
- try to use the official Perl client for comparison
- if you need to use a proxy server to connect, make sure it is set in your Java code

I have received similar reports that turned out to be network or hardware issues.

**Comment by androideveloper** [comment]
Hi, the issue is resolved! It was due to our network settings! Thanks!
