### ISSUE TITLE
MOSS Server does not recognize this programming language

### ISSUE THREAD

**Issue by ShobhitMaheshwari** [nordicway/moji#9]
Thank you for this repository. However I'm encountering an error.

I'm working with master branch of this repo(commit id: 586c0c1ff4b0f7aecf83fd7cd085685320d22952). I just changed the files path and basefiles path. I did not even change the language. The stacktrace is:

Exception in thread "main" it.zielke.moji.MossException: MOSS Server does not recognize this programming language
	at it.zielke.moji.SocketClient.sendLanguage(SocketClient.java:348)
	at it.zielke.moji.SocketClient.run(SocketClient.java:242)
	at example.QuickStart.main(QuickStart.java:35)

serverString is null at line 345 in file SocketClient.java

You may check it in [my forked repo](https://github.com/ShobhitMaheshwari/moji) (master branch, commit id: ece0ed7112705559a3b8ff83b503e18a22d7d750). Please help.

**Comment by nordicway** [comment]
Can you try again with absolute paths?

**Comment by nordicway** [comment]
Also make sure you obtain a valid MOSS account from the website and enter the user id.
This is an error during the initialization stage so it could also be a temporary problem with the MOSS server.

**Comment by oskar5331** [comment]
Hi, I have the same error and serverString is null, @ShobhitMaheshwari did you get it to work?
Since it was made some time ago then I have doubts if this still working or not? 

I have a project where I'm trying to get it to working again but no luck. I have tried several days, renewed the id, I have tested the connection with this command: "nc -v -u -z  moss.stanford.edu 7690" and it succeeds.

Code where is implemented is here:
`               if (!plagiarismPath.endsWith("/")) plagiarismPath += "/";
		String path = plagiarismPath + taskName;

		//code from https://github.com/nordicway/moji
		Collection<File> studentFiles = getStudentFiles(path);
		SocketClient client = getSocketClient();
		client.setUserID(mossUserId);
		try {
			client.setLanguage("java");
			client.run();
			for (File file : studentFiles) {
				client.uploadFile(file);
			}
			System.out.println(client.getCurrentStage() == Stage.AWAITING_QUERY);
			client.sendQuery();
			URL results = client.getResultURL();
			existingPlagiarism.setResult(results.toString());
			return plagiarismRepository.save(existingPlagiarism);
		} catch (MossException | IOException e) {
			e.printStackTrace();
		}`

Would be nice to get it to work again :)

**Comment by oskar5331** [comment]
Haha, found out that previeously userId was passed in with quotes, that's why nothing worked. Now I got it to work.
